name: test workflow
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gbrls/action-upload-secret@main
        with:
          secret-name: 'UNIVERSE_KEY'
          secret-value: '42'
      - name: List artifacts
        run: |
          ls -la
          find
